name: Test build and deploy application
on: 
 workflow_dispatch:

 push:
  branches: 
    - main
 pull_request:
  branches:
    - main
jobs:
 test:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v4
  - name: Cache python dependencies
    uses: actions/cache@v4
    with:
      path: ~/.cache/pip
      key: ${{ runner.os}}-pip-{{ hashFiles('**/requirements.txt') }}
      restore-keys:
       ${{ runner.os }}-pip-
  - name: set up JDK 21
    uses: actions/setup-java@v3
    with:
      java-version: '21'
      distribution: 'temurin'
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
        python-version: '3.11' 
  - name: Install dependencies
    run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  - name: Run tests with coverage
    run: |
        pip install pytest pytest-cov
        pytest tests/test_routes.py --cov=app --cov-report=xml:coverage.xml
        

  
