name: Test build and deploy application
on: 
 workflow_dispatch:

 push:
  branches: 
    - main
 pull_request:
  branches:
    - main
jobs:
 test:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v4
  - name: Cache python dependencies
    uses: actions/cache@v4
    with:
      path: ~/.cache/pip
      key: ${{ runner.os}}-pip-{{ hashFiles('**/requirements.txt') }}
      restore-keys:
       ${{ runner.os }}-pip-
  - name: set up JDK 21
    uses: actions/setup-java@v3
    with:
      java-version: '21'
      distribution: 'temurin'
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
        python-version: '3.11' 
  - name: Install dependencies
    run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  - name: Run tests with coverage
    run: |
        pip install pytest pytest-cov
        pytest tests --cov=app --cov-report=xml:coverage.xml
        
 sonarqube:
  runs-on: ubuntu-latest
  needs: test
  steps:  
  - name: Checkout code
    uses: actions/checkout@v4
  - name: SonarCloud Scan
    uses: sonarsource/sonarqube-scan-action@v5.2.0
    env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_PAT }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    with:
      args: >
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.projectName=${{ github.event.repository.name }}
          -Dsonar.python.version=3.11
          -Dsonar.sources=app
          -Dsonar.tests=tests
          -Dsonar.python.coverage.reportPaths=coverage.xml
   
  
